---
deployment:
  tasks:
    - export DEPLOYPATH=/home/artigqkc/artisticdecor.in/
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH